### ISSUE TITLE
Failure to execute a process caused by undocumented requirement to start a shell

### ISSUE THREAD

**Issue by lostdistance** [slicer69/sysvinit#1]
While developing an embedded system started by /sbin/init, I encountered a failure to execute a process in /etc/inittab. The process was a simple mount command:

/bin/mount -n -t devpts -o gid=5,mode=620 none /dev/pts

The cause of the failure was the '=' character in the mount command line. Upon investigation I found that /sbin/init interprets certain characters (including '=') as a requirement to start a shell:

...
  } else if (strpbrk(proc, "~`!$^&*()=|\\{}[];\"'<>?")) {
  /* See if we need to fire off a shell for this command */
        /* Give command line to shell */
        args[1] = SHELL;
        args[2] = "-c";
        strcpy(buf, "exec ");
        strncat(buf, proc, sizeof(buf) - strlen(buf) - 1);
        args[3] = buf;
        args[4] = NULL;
  } else {
...

My embedded system did not have a shell (deliberately). Consequently /sbin/init failed to execute the process.

My fix was to patch the /sbin/init source code to remove the preceding code block.

May I recommend one or more of the following courses of action (in increasing order of severity):
1. Document this behaviour, whereby the presence of certain characters within the process command line introduces a requirement to start a shell.
2. Provide an option whereby this behaviour can be disabled. This will preserve compatibility with existing /etc/inittab files.
3. Remove this behaviour completely if it is not required. Obviously this will break compatibility with existing /etc/inittab files if they have come to depend on it.

Note that providing an option to disable this behaviour may be desirable for other reasons, such as quicker boot times.

**Comment by slicer69** [comment]
Thanks for the bug report.

Personally I'm in favour of a combination of #2 with #1: offer a way to disable this behaviour and then document it so situations like this are clear.

Maybe the inittab file should support a toggle for disabling the shell. Something like...  a "*"prefixing the line forces it to be read "as is" after the star symbol.

Could you please post the block of your inittab file where the mount command was included for context? I want to make sure I have a clear image of what was happening at the time.

**Comment by lostdistance** [comment]
Thank you for your response.

Here is the block of my inittab for reference:

~~::sysinit:/bin/mount -n -t proc none /proc
~~::sysinit:/bin/mount -n -t sysfs none /sys
~~::sysinit:/bin/mount -n -t devtmpfs -o size=1m,nr_inodes=1k,mode=755 none /dev
~~::sysinit:/bin/ln -s /proc/self/fd /dev/fd
~~::sysinit:/bin/mkdir /dev/pts
~~::sysinit:/bin/mount -n -t devpts -o gid=5,mode=620 none /dev/pts
~~::sysinit:/bin/mount -n -t tmpfs -o size=1m,nr_inodes=1k,mode=755 none /run
~~::sysinit:/bin/cp /dev/null /run/resolv.conf
~~::sysinit:/bin/mount -n -t tmpfs -o size=128m,nr_inodes=128k,mode=1777 none /tmp

**Comment by slicer69** [comment]
I'm going to propose that process commands in the inittab file which start with an @ symbol indicate the command is to be taken literally (including equal signs, brackets, etc).

For example, a line in your inittab file would change from
       ~~::sysinit:/bin/mount -n -t devpts -o gid=5,mode=620 none /dev/pts

to

      ~~::sysinit:@/bin/mount -n -t devpts -o gid=5,mode=620 none /dev/pts

I'm attaching a patch which I think will handle this situation, basically forcing init to skip trying to launch a shell and instead run the command literally. Please try it out and let me know if it works for you?

[issue-1.txt](https://github.com/slicer69/sysvinit/files/8054699/issue-1.txt)

**Comment by lostdistance** [comment]
Thank you for the patch.

Yes, it does work.

The only issue I found was that the vim syntax highlighting for /etc/inittab complains about the new '@' character. But that is for another day.
