### ISSUE TITLE
Glibc 2.36: incompatibility sys/mount.h and linux/fs.h (linux/mount.h)

### ISSUE THREAD

**Issue by lucascars** [slicer69/sysvinit#10]
Starting from glibc-2.36, sys/mount.h and linux/mount.h could not be included in the same source file:

https://sourceware.org/glibc/wiki/Release/2.36#Usage_of_.3Clinux.2Fmount.h.3E_and_.3Csys.2Fmount.h.3E

It seems safe to remove "#include <linux/fs.h>" from sulogin.c also for previous glibc versions.
[sysvinit.remove_linux_fs.diff.txt](https://github.com/slicer69/sysvinit/files/9279822/sysvinit.remove_linux_fs.diff.txt)

**Comment by slicer69** [comment]
Thank you for the patch. I've tested this change against glibc 2.21 and confirmed it still works (sulogin builds and runs). 

I'll include this fix in the next version of sysvinit (3.03).
