### ISSUE TITLE
3.05 release not available via nongnu mirrors

### ISSUE THREAD

**Issue by thesamesam** [slicer69/sysvinit#12]
3.05, unlike previously releases, does not appear to be available via the nongnu mirror network. Is this intentional? If so, could you consider updating the Savannah page to make it clear?

Thanks!

**Comment by slicer69** [comment]
Yes, this is intentional. As was announced with the previous few releases, SysV init has been migrating away from using Savannah.

In fact, the front page of the SysV Savannah page points to this GitHub project, as does the links for downloading and accessing source code.

**Comment by thesamesam** [comment]
> Yes, this is intentional. As was announced with the previous few releases, SysV init has been migrating away from using Savannah.
> 
> In fact, the front page of the SysV Savannah page points to this GitHub project, as does the links for downloading and accessing source code.

No, I get that, but "Downloads" on Savannah still sends me to https://savannah.nongnu.org/files/?group=sysvinit, and I don't think anything on the page is clearly saying "You can't even download things here anymore".

I suggest adding something explicit like "This project page is no longer maintained, please see the respective repositories linked below on github for downloads, development, bug report, and any other reosurces."

**Comment by thesamesam** [comment]
ping?

**Comment by slicer69** [comment]
I want to leave the download link for legacy purposes. It may be hardwired anyway for Savannah mirrors. As for a README or similar file, I'm not sure what the point is. If people don't read the web page or the mailing list or the release notes, they're probably not going to download and go through a README file either.
