### ISSUE TITLE
Location of translated man-pages.

### ISSUE THREAD

**Issue by zarniwhoop73** [slicer69/sysvinit#14]
Somebody pointed to this repo, and I can now see from closed issues that it is a successor to savannah. and uses ROOT= to do the same as DESTDIR=. However:

1. I was told that it installs its translations in /usr/share/man/man5{de,es,fr,pl} whereas the standard appears to be /usr/share/man/{lang}/manN (2019 report from ubuntu, current installs on LFS and BLFS).

2. Using ROOT= failed quickly in the first (man1/de) translations, so I could not confirm the others are also in non-standard places:

`for man in last.1 lastb.1 mesg.1 readbootlog.1 utmpdump.1 wall.1 de/last.1  de/mesg.1 de/readbootlog.1 de/utmpdump.1 de/wall.1; do \
		install -m 644 ../man/$man /tmp/SYSV/usr/share/man/man1/$man; \
		sed -i "1{ s@^\('\\\\\"\)[^\*-]*-\*- coding: [^[:blank:]]\+ -\*-@\1@; }" /tmp/SYSV/usr/share/man/man1/$man ; \
	done

install: cannot create regular file '/tmp/SYSV/usr/share/man/man1/de/last.1': No such file or directory

sed: can't read /tmp/SYSV/usr/share/man/man1/de/last.1: No such file or directory

install: cannot create regular file '/tmp/SYSV/usr/share/man/man1/de/mesg.1': No such file or directory

sed: can't read /tmp/SYSV/usr/share/man/man1/de/mesg.1: No such file or directory

install: cannot create regular file '/tmp/SYSV/usr/share/man/man1/de/readbootlog.1': No such file or directory

sed: can't read /tmp/SYSV/usr/share/man/man1/de/readbootlog.1: No such file or directory

install: cannot create regular file '/tmp/SYSV/usr/share/man/man1/de/utmpdump.1': No such file or directory

sed: can't read /tmp/SYSV/usr/share/man/man1/de/utmpdump.1: No such file or directory

install: cannot create regular file '/tmp/SYSV/usr/share/man/man1/de/wall.1': No such file or directory

sed: can't read /tmp/SYSV/usr/share/man/man1/de/wall.1: No such file or directory

make[1]: *** [Makefile:210: install] Error 2
`

**Comment by slicer69** [comment]
I cannot replicate this error message. What are the exact commands used to build and install SysV init? It looks like it might be "make ROOT=/tmp/SYSV install", but that works on my system as long as the user running make has write access to /tmp.

**Comment by zarniwhoop73** [comment]
For the shipped version, I have foregotten what I was doing at that time.  Rerunning

make
make ROOT=/tmp/SYSV install

The output on stderr is
install: cannot create regular file '/tmp/SYSV/usr/share/man/man1/de/last.1': No such file or directory
sed: can't read /tmp/SYSV/usr/share/man/man1/de/last.1: No such file or directory
install: cannot create regular file '/tmp/SYSV/usr/share/man/man1/de/mesg.1': No such file or directory
sed: can't read /tmp/SYSV/usr/share/man/man1/de/mesg.1: No such file or directory
install: cannot create regular file '/tmp/SYSV/usr/share/man/man1/de/readbootlog.1': No such file or directory
sed: can't read /tmp/SYSV/usr/share/man/man1/de/readbootlog.1: No such file or directory
install: cannot create regular file '/tmp/SYSV/usr/share/man/man1/de/utmpdump.1': No such file or directory
sed: can't read /tmp/SYSV/usr/share/man/man1/de/utmpdump.1: No such file or directory
install: cannot create regular file '/tmp/SYSV/usr/share/man/man1/de/wall.1': No such file or directory
sed: can't read /tmp/SYSV/usr/share/man/man1/de/wall.1: No such file or directory
make[1]: *** [Makefile:210: install] Error 2
make: *** [Makefile:7: install] Error 2

The installed files are:SYSV/:
total 0
drwxr-xr-x 2 ken users  60 Dec  1 02:06 bin
drwxr-xr-x 3 ken users  60 Dec  1 02:05 etc
drwxr-xr-x 2 ken users 280 Dec  1 02:06 sbin
drwxr-xr-x 5 ken users 100 Dec  1 02:05 usr

SYSV/bin:
total 0
lrwxrwxrwx 1 ken users 14 Dec  1 02:06 pidof -> /sbin/killall5

SYSV/etc:
total 0
drwxr-xr-x 2 ken users 40 Dec  1 02:05 inittab.d

SYSV/etc/inittab.d:
total 0

SYSV/sbin:
total 284
-rwxr-xr-x 1 ken users 27880 Dec  1 02:06 bootlogd
-rwxr-xr-x 1 ken users 16264 Dec  1 02:06 fstab-decode
-rwxr-xr-x 1 ken users 27400 Dec  1 02:06 halt
-rwxr-xr-x 1 ken users 61544 Dec  1 02:06 init
-rwxr-xr-x 1 ken users 32232 Dec  1 02:06 killall5
-rwxr-xr-x 1 ken users 17760 Dec  1 02:06 logsave
lrwxrwxrwx 1 ken users     4 Dec  1 02:06 poweroff -> halt
lrwxrwxrwx 1 ken users     4 Dec  1 02:06 reboot -> halt
-rwxr-xr-x 1 ken users 16624 Dec  1 02:06 runlevel
-rwxr-xr-x 1 ken users 37624 Dec  1 02:06 shutdown
-rwxr-xr-x 1 ken users 33872 Dec  1 02:06 sulogin
lrwxrwxrwx 1 ken users     4 Dec  1 02:06 telinit -> init

SYSV/usr:
total 0
drwxr-xr-x 2 ken users 160 Dec  1 02:06 bin
drwxr-xr-x 2 ken users  60 Dec  1 02:06 include
drwxr-xr-x 3 ken users  60 Dec  1 02:05 share

SYSV/usr/bin:
total 112
-rwxr-xr-x 1 ken users 27504 Dec  1 02:06 last
lrwxrwxrwx 1 ken users     4 Dec  1 02:05 lastb -> last
-rwxr-xr-x 1 ken users 16816 Dec  1 02:06 mesg
-rwxr-xr-x 1 ken users 16640 Dec  1 02:06 readbootlog
-rwxr-xr-x 1 ken users 17768 Dec  1 02:06 utmpdump
-rwxr-xr-x 1 ken users 22608 Dec  1 02:06 wall

SYSV/usr/include:
total 4
-rw-r--r-- 1 ken users 2446 Dec  1 02:06 initreq.h

SYSV/usr/share:
total 0
drwxr-xr-x 5 ken users 100 Dec  1 02:05 man

SYSV/usr/share/man:
total 0
drwxr-xr-x 2 ken users 160 Dec  1 02:06 man1
drwxr-xr-x 2 ken users  40 Dec  1 02:05 man5
drwxr-xr-x 2 ken users  40 Dec  1 02:05 man8

SYSV/usr/share/man/man1:
total 28
-rw-r--r-- 1 ken users 4374 Dec  1 02:06 last.1
-rw-r--r-- 1 ken users   16 Dec  1 02:06 lastb.1
-rw-r--r-- 1 ken users 1858 Dec  1 02:06 mesg.1
-rw-r--r-- 1 ken users 1752 Dec  1 02:06 readbootlog.1
-rw-r--r-- 1 ken users 1914 Dec  1 02:06 utmpdump.1
-rw-r--r-- 1 ken users 1945 Dec  1 02:06 wall.1

SYSV/usr/share/man/man5:
total 0

SYSV/usr/share/man/man8:
total 0

and loads of space:

Filesystem     1K-blocks    Used Available Use% Mounted on
tmpfs           16127896 5489604  10638292  35% /tmp

**Comment by slicer69** [comment]
Thank you for walking me through it.

I think this has been fixed already in the most recent development branch, 3.06. You can test and confirm whether this has been resolved by checking out the 3.06 branch here: https://github.com/slicer69/sysvinit/tree/3.06

Alternatively, waiting until the upcoming release, which should be later this month, I believe will fix the issue.

I'm going to close this report for now. However, if the problem appears in version 3.06 please re-open this bug report.
