### ISSUE TITLE
Destdir option

### ISSUE THREAD

**Issue by Shifulor** [slicer69/sysvinit#2]
Hi there guys. First of all many thanks for your hard work on this great init system. I am currently building a (still linux based) OS and am trying to make binary of sysvinit. However it seems unable to use the DESTDIR variable which according to make standards should install uinto a specified dir. Does sysv have any simmilar function that i have not seen? Many thanks!

**Comment by slicer69** [comment]
At the moment SysV init doesn't support DESTDIR (a side effect of its age and no one asking for it before, I guess). However, the package does have an equivalent. It uses the variable ROOT as a prefix for install directories.

So for example, running the following should work:

     make
     cd src
     make ROOT=/some/test/path install

This will install sysvinit into /some/test/path/sbin 
Toward the end of the src/Makefile is where the install happens and you can see the specific steps used.

**Comment by Shifulor** [comment]
That worked, thank you very much :D By the way also thanks for maintaining great programs like this, but also doas :))

**Comment by slicer69** [comment]
My pleasure. Glad that worked for you.
