### ISSUE TITLE
Process command line limited to 127 char and 15  args max

### ISSUE THREAD

**Issue by didgaudin** [slicer69/sysvinit#24]
Hi,
is it possible to extend this limit? or is there a reason for this limit to be hardcoded in init.c?

**Comment by slicer69** [comment]
Since init only takes a maximum of four possible command line options (most of them one character long), why would you ever run into a limit of 15, or more than 127 characters?

**Comment by didgaudin** [comment]
This is to be able to launch services with init and the respawn functionality.

**Comment by slicer69** [comment]
Services aren't launched from the init command line.
