### ISSUE TITLE
ctime could return NULL，in list function should judge the return value

### ISSUE THREAD

**Issue by freetime312** [slicer69/sysvinit#26]
<img width="1079" alt="image" src="https://github.com/user-attachments/assets/8673b364-025e-4036-9ba9-642e563938de">
we will get segment fault when the /var/log/btmp file changed invalud，so  the ctime return value needs to be interpreted

**Comment by slicer69** [comment]
Agreed, I'll fix this and look for other places we might assume the return value of ctime().

**Comment by slicer69** [comment]
I found about eight places where we were relying on the return value of ctime().

Also found two places where we were assuming the length of the string ctime() returns.

Technically, it should be virtually impossible for ctime() to fail on a halfway functional system or, as the original post mentions, if it's fed invalid data from a root-owned file. Still, it's good to be proactive so I've added checks for all ctime() calls and removed assumptions about the length of the returned string.

Please test the new 3.12 branch, where I have committed the fixes, and let me know if you encounter any issues.

**Comment by freetime312** [comment]
Now it works normally

**Comment by slicer69** [comment]
Great, I'll include this change in the next version of sysvinit. Thanks for testing the update.
