### ISSUE TITLE
Potentiallly stupid question

### ISSUE THREAD

**Issue by Shifulor** [slicer69/sysvinit#4]
I think this is a pretty stupid question, if you are good with sysv, but im not :smile: Since there are not many docs for it online i got my info from the LFS book. according to that i need to use their additional bootscripts, however i am wondering do i really have to?? It looks like all needed programms like halt are already there, so i wonder weather the "lfs-bootscripts" are neccessary

**Comment by slicer69** [comment]
I'm not familiar with the LFS bootscripts. However, I'm guessing they are a collection of shell scripts that bring services online. Debian has a similar package called initscripts, if I'm not mistaken.

SysV init provides programs like halt, shutdown, pidof, etc. But these don't handle services. Usually bootscripts (or initscripts) manage services like DBUS, login, X11, etc. So if your operating system does anything, except booting and shutting down, you need something to manage services.

Most operating systems that run on SysV init use scripts, but some take other approaches, like running the OpenRC service manager. You still need to have something that configures the background services though.

**Comment by Shifulor** [comment]
Mhm, but these bootscripts are not for external services, but rather only sysv specific management. They contain these scripts `checkfs, cleanfs, console, functions, halt, ifdown, ifup, localnet, modules, mountfs, mountvirtfs, network, rc, reboot, sendsignals, setclock, ipv4-static, swap, sysctl, sysklogd, template, udev, and udev_retry` and while not all of these are in the base sysv, these script seem kind of obsolete to me, am i wrong? I do not wish to create a bloated system, and if the user wants these, user can install them themselves, so i am sorry to annoy you with such a 'unrealted' question, but i want rather pure sysv. Will it work fine with out these scripts? Ofcourse i wil make scripts for services like sshd etc.:)

**Comment by slicer69** [comment]
I'm not familiar with the contents of the LFS scripts so I cant' say for sure. But those all look like names of services, ones which would be critical to a working system.

Unless you have custom scripts to do what these scripts/services do then your operating system isn't going to do anything.
