### ISSUE TITLE
GPG key for verification

### ISSUE THREAD

**Issue by atsampson** [slicer69/sysvinit#6]
The 3.03 release tarball is signed with a different GPG key from the previous releases, and there's no indication of where to obtain this key from for distributors to verify the release.

It'd be best to have a clear indication on the sysvinit web site (which I guess is the repo's README) of what keys are allowed to sign releases, and announce changes separately ahead of time.

**Comment by slicer69** [comment]
Sure, I'll add a section to the README. If you're looking to verify the key, it's available to download from the Savannah mirror (as sysvinit-verification-key-2) and it can be found on keys.openpgp.org

**Comment by atsampson** [comment]
Lovely, thanks!
