### ISSUE TITLE
Hurd build fails: ./src/bootlogd.c:358: undefined reference to `major'

### ISSUE THREAD

**Issue by markhindley** [slicer69/sysvinit#7]
Build of 3.03 on Hurd fails with undefined references to major and minor.

[Debian Hurd i386 build log.](https://buildd.debian.org/status/fetch.php?pkg=sysvinit&arch=hurd-i386&ver=3.03-1&stamp=1650105984&raw=0)

A quick look suggests that src/bootlogd.c #include <sys/sysmacros.h>  is only within #ifdef __linux__, so those macros are not defined on Hurd.

Mark

**Comment by slicer69** [comment]
Thanks for letting me know. Could you check to see if bootlogd compiles on Hurd if sys/sysmarcos.h is included? If so this will be an easy fix. On the other hand, if the macros aren't defined at all on Hurd then we may need to get a more involved compatibility fix.

**Comment by markhindley** [comment]
Jesse,

On Sat, Apr 16, 2022 at 02:39:53PM +0000, Jesse Smith wrote:
>    Thanks for letting me know. Could you check to see if bootlogd compiles
>    on Hurd if sys/sysmarcos.h is included?

I have just tried a build on the Debian Hurd porterbox. It builds with the
following patch.

--- src/bootlogd.c.orig	2022-04-16 18:42:34.000000000 +0000
+++ src/bootlogd.c	2022-04-16 18:42:50.000000000 +0000
@@ -41,9 +41,9 @@
 #include <getopt.h>
 #include <dirent.h>
 #include <fcntl.h>
+#include <sys/sysmacros.h>
 #ifdef __linux__
 #include <pty.h>
-#include <sys/sysmacros.h>
 #endif
 
 #ifdef __FreeBSD__


But I am not sure it is necessary for BSD so it may need

#ifdef __linux__ || __GNU__

or similar.

It is my first experience with GNU Hurd, so the opinion of an actual user may be
more valuable!

Mark

**Comment by slicer69** [comment]
I've applied the change, using the "if defined linux || GNU" approach. Seems to be working, at least on Linux. Please let me know if the 3.04 branch I just pushed builds on Hurd?

**Comment by markhindley** [comment]
Jesse,

On Sat, Apr 16, 2022 at 07:13:53PM +0000, Jesse Smith wrote:
>    I've applied the change, using the "if defined linux || GNU" approach.
>    Seems to be working, at least on Linux. Please let me know if the 3.04
>    branch I just pushed builds on Hurd?

I have just built it with no issues on Hurd.

Thanks.

Mark

**Comment by slicer69** [comment]
Great, I'm going to mark this as fixed and the change will be in the next version.
